name: Python Pipeline

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell 
      - name: Test the Python script "lambda_function.py"
        run: python lambda_function.py
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are any Flake 8 issues
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 .
      - name: Unit Tests
        run: |
          # Run unittest 
          python -m unittest "unit_tests.py"
  package-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Make the directory
        run: |
          mkdir -p ./artifacts/${{ github.repository }}
          ls ${{ github.workspace }}
      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r package.zip lambda_function.py
      - name: Move file to artifacts directory
        run: mv package.zip ./artifacts
      - name: List files in the artifacts directory
        run: |
          cd ./artifacts && ls
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: push zip to S3
        run: |
          aws s3 sync './artifacts/.' s3://cetm67-ad-package-storage
      - name: Job Stats
        run: echo "🍏 This job's status is ${{ job.status }}."
